language: elixir
sudo: false
elixir:
  - 1.6.4
otp_release:
  - 20.3

env:
  - MIX_ENV=test RUNNER_API_USER=test-runner RUNNER_API_KEY=test RUNNER_API_URL=http://localhost.com:4000/runner-api

before_script:
  - mix deps.compile
  - mix compile --warnings-as-errors

script:
  - mix format --check-formatted
  - mix test

cache:
  directories:
    - _build
    - deps
